
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-frontiers-s25-09
owner: ucsb-cs156-s25
repo_name: proj-frontiers-s25-09
pull_requests: [{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-2","number":29,"title":"Andrewkim102 2","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-09/pull/29"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-1","number":28,"title":"AK - WIP, but includes a strong framework for the startup code similar to proj-courses","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-09/pull/28"},{"author":{"id":"U_kgDOB3DxTg","is_bot":false,"login":"moiez12","name":""},"headRefName":"MB-issue01","number":27,"title":"MB-Issue01, Add GitHub Organization Status Job with on-demand Swagger endpoint","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-09/pull/27"}]
