
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/proj-frontiers-s25-09
owner: ucsb-cs156-s25
repo_name: proj-frontiers-s25-09
pull_requests: [{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-5-2","number":59,"title":"AK - application-development.properties Adjustment #2","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-09/pull/59"},{"author":{"id":"U_kgDOB3DxTg","is_bot":false,"login":"moiez12","name":""},"headRefName":"MB-issue01-v2small","number":56,"title":"MB-issue01-v2small, Fixed 403 Issue for Google Github Login for Null","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-09/pull/56"},{"author":{"id":"U_kgDOB3DxTg","is_bot":false,"login":"moiez12","name":""},"headRefName":"MB-RosterStudentTable-v2","number":49,"title":"MB- add roster student table, stories, and tests","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-09/pull/49"},{"author":{"id":"U_kgDOB3DmRQ","is_bot":false,"login":"andrewkim102","name":"Andrew Kim"},"headRefName":"andrewkim102-5","number":46,"title":"AK - H2 Admin Table Displaying ALL Admin Emails","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-09/pull/46"},{"author":{"id":"U_kgDOB3DxTg","is_bot":false,"login":"moiez12","name":""},"headRefName":"MB-issue01","number":27,"title":"DRAFT MB-Issue01, Add GitHub Organization Status Job with on-demand Swagger endpoint","url":"https://github.com/ucsb-cs156-s25/proj-frontiers-s25-09/pull/27"}]
